services:
  server:
    environment:
      STATAPI_DB: postgresql+asyncpg://statapi:test@172.16.0.11:5432/statapi # ПОМЕНЯТЬ НА БОЛЕЕ УСТОЙЧИВЫЕ ПАРОЛИ
      STATAPI_STATIC: /app/static/
      STATAPI_CONFIG: /app/config.yaml
      STATAPI_ACCESS_SECRET: secret # ЗАМЕНИТЬ НА РЕАЛЬНЫЙ СЕКРЕТ
      STATAPI_REFRESH_SECRET: secret # ЗАМЕНИТЬ НА РЕАЛЬНЫЙ СЕКРЕТ
    build: .
    ports:
      - "8080:8080"
    volumes:
      - app:/app/static
      - ./config.yaml:/app/config.yaml
    networks:
      front-tier:
        ipv4_address: 172.16.0.10
  database:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "statapi"
      POSTGRES_USER: "statapi"
      POSTGRES_PASSWORD: "test" # ПОМЕНЯТЬ НА БОЛЕЕ УСТОЙЧИВЫЕ ПАРОЛИ
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      front-tier:
        ipv4_address: 172.16.0.11

volumes:
  app:
  db-data:

networks:
  front-tier:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"
