"""Add role based auth models

Revision ID: 63ec4b49750b
Revises: 36eaca93b5fb
Create Date: 2025-09-30 17:12:08.887623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '63ec4b49750b'
down_revision: Union[str, None] = '36eaca93b5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('rights',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('login', sa.String(length=255), nullable=False),
                    sa.Column('hash', sa.String(length=255), nullable=False),
                    sa.Column('token', sa.String(length=255), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login')
                    )
    op.create_table('role_right_goals',
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('right_id', sa.Integer(), nullable=False),
                    sa.Column('goal_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['right_id'], ['rights.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('role_id', 'right_id', 'goal_id')
                    )
    op.create_table('user_roles',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'role_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('role_right_goals')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('rights')
    op.drop_table('goals')
    # ### end Alembic commands ###
