"""add can_grant to role_right_goals

Revision ID: d38504baa564
Revises: c1a2f3e4d5b6
Create Date: 2026-04-22 16:47:00.263301

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d38504baa564"
down_revision: Union[str, None] = "c1a2f3e4d5b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role_right_goals", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "can_grant", sa.Boolean(), server_default=sa.false(), nullable=False
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role_right_goals", schema=None) as batch_op:
        batch_op.drop_column("can_grant")
    # ### end Alembic commands ###
