"""Deleting all dod models

Revision ID: 559105c435f6
Revises: a1b2c3d4e5f6
Create Date: 2026-05-11 22:38:23.639530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559105c435f6'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dod_statics')
    op.drop_table('dod_corpuses')
    op.drop_table('dod_aud_photo')
    op.drop_table('dod_locations')
    op.drop_table('dod_auditories')
    op.drop_table('dod_plans')
    op.drop_table('dod_types')
    op.drop_table('dod_floors')
    with op.batch_alter_table('user_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_logs_user_id'))

    op.create_table(
        'dod_floors',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('name', sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table(
        'dod_types',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table(
        'dod_plans',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('id_sys', sa.VARCHAR(length=20), nullable=False),
        sa.Column('cor_id', sa.INTEGER(), nullable=False),
        sa.Column('floor_id', sa.INTEGER(), nullable=False),
        sa.Column('ready', sa.BOOLEAN(), nullable=False),
        sa.Column('entrances', sa.TEXT(), nullable=False),
        sa.Column('graph', sa.TEXT(), nullable=False),
        sa.Column('svg_id', sa.INTEGER(), nullable=True),
        sa.Column('nearest_entrance', sa.VARCHAR(length=50), nullable=True),
        sa.Column('nearest_man_wc', sa.VARCHAR(length=50), nullable=True),
        sa.Column('nearest_woman_wc', sa.VARCHAR(length=50), nullable=True),
        sa.Column('nearest_shared_wc', sa.VARCHAR(length=50), nullable=True),
        sa.ForeignKeyConstraint(['cor_id'], ['dod_corpuses.id'], ),
        sa.ForeignKeyConstraint(['floor_id'], ['dod_floors.id'], ),
        sa.ForeignKeyConstraint(['svg_id'], ['dod_statics.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id_sys')
    )
    op.create_table(
        'dod_auditories',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('id_sys', sa.VARCHAR(length=50), nullable=False),
        sa.Column('type_id', sa.INTEGER(), nullable=False),
        sa.Column('ready', sa.BOOLEAN(), nullable=False),
        sa.Column('plan_id', sa.INTEGER(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=20), nullable=False),
        sa.Column('text_from_sign', sa.VARCHAR(length=200), nullable=True),
        sa.Column('additional_info', sa.VARCHAR(length=200), nullable=True),
        sa.Column('comments', sa.VARCHAR(length=200), nullable=True),
        sa.Column('link', sa.VARCHAR(length=255), nullable=True),
        sa.ForeignKeyConstraint(['plan_id'], ['dod_plans.id'], ),
        sa.ForeignKeyConstraint(['type_id'], ['dod_types.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'dod_locations',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('id_sys', sa.VARCHAR(length=2), nullable=False),
        sa.Column('name', sa.VARCHAR(length=25), nullable=False),
        sa.Column('short', sa.VARCHAR(length=2), nullable=False),
        sa.Column('ready', sa.BOOLEAN(), nullable=False),
        sa.Column('address', sa.VARCHAR(length=100), nullable=False),
        sa.Column('metro', sa.VARCHAR(length=100), nullable=False),
        sa.Column('crossings', sa.TEXT(), nullable=True),
        sa.Column('comments', sa.VARCHAR(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id_sys')
    )
    op.create_table(
        'dod_aud_photo',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('aud_id', sa.INTEGER(), nullable=False),
        sa.Column('ext', sa.VARCHAR(length=6), nullable=False),
        sa.Column('name', sa.VARCHAR(length=50), nullable=False),
        sa.Column('path', sa.VARCHAR(length=255), nullable=False),
        sa.Column('link', sa.VARCHAR(length=255), nullable=False),
        sa.Column('creation_date', sa.DATETIME(), nullable=False),
        sa.Column('update_date', sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(['aud_id'], ['dod_auditories.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table(
        'dod_corpuses',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('id_sys', sa.VARCHAR(length=7), nullable=False),
        sa.Column('loc_id', sa.INTEGER(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=20), nullable=False),
        sa.Column('ready', sa.BOOLEAN(), nullable=False),
        sa.Column('stair_groups', sa.TEXT(), nullable=True),
        sa.Column('comments', sa.VARCHAR(length=100), nullable=True),
        sa.ForeignKeyConstraint(['loc_id'], ['dod_locations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id_sys')
    )
    op.create_table(
        'dod_statics',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('ext', sa.VARCHAR(length=6), nullable=False),
        sa.Column('path', sa.VARCHAR(length=255), nullable=False),
        sa.Column('name', sa.VARCHAR(length=50), nullable=False),
        sa.Column('link', sa.VARCHAR(length=255), nullable=False),
        sa.Column('creation_date', sa.DATETIME(), nullable=False),
        sa.Column('update_date', sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
