"""Fix tg bot data structure

Revision ID: 84c9b51dc5fc
Revises: 7f385d04c10a
Create Date: 2026-03-19 15:01:23.945391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c9b51dc5fc'
down_revision: Union[str, None] = '7f385d04c10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tg_event_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_event_types_name'))
        batch_op.create_index(batch_op.f('ix_tg_event_types_name'), ['name'], unique=True)

    with op.batch_alter_table('tg_users', schema=None) as batch_op:
        batch_op.alter_column('creation_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_tg_users_tg_id'))
        batch_op.create_index(batch_op.f('ix_tg_users_tg_id'), ['tg_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tg_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_users_tg_id'))
        batch_op.create_index(batch_op.f('ix_tg_users_tg_id'), ['tg_id'], unique=False)
        batch_op.alter_column('creation_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('tg_event_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_event_types_name'))
        batch_op.create_index(batch_op.f('ix_tg_event_types_name'), ['name'], unique=False)

    # ### end Alembic commands ###
