"""Drop all old tables

Revision ID: 213a69474d75
Revises: e2f4a6b8c0d1
Create Date: 2026-05-04 04:11:42.706136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213a69474d75'
down_revision: Union[str, None] = 'e2f4a6b8c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ids')
    with op.batch_alter_table('site_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_statistics_id'))

    op.drop_table('site_statistics')
    with op.batch_alter_table('tg_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_users_creation_date'))
        batch_op.drop_index(batch_op.f('ix_tg_users_id'))
        batch_op.drop_index(batch_op.f('ix_tg_users_tg_id'))

    op.drop_table('tg_users')
    with op.batch_alter_table('tg_event_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_event_types_id'))
        batch_op.drop_index(batch_op.f('ix_tg_event_types_name'))

    op.drop_table('tg_event_types')
    with op.batch_alter_table('selected_auditories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_selected_auditories_id'))

    op.drop_table('selected_auditories')
    with op.batch_alter_table('started_ways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_started_ways_id'))

    op.drop_table('started_ways')
    with op.batch_alter_table('changed_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_changed_plans_id'))

    op.drop_table('changed_plans')
    with op.batch_alter_table('tg_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_events_event_type_id'))
        batch_op.drop_index(batch_op.f('ix_tg_events_id'))
        batch_op.drop_index(batch_op.f('ix_tg_events_tg_id'))
        batch_op.drop_index(batch_op.f('ix_tg_events_time'))

    op.drop_table('tg_events')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_client_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'client_ids', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_client_id'), 'client_ids', ['client_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    op.create_table('tg_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.DATETIME(), nullable=False),
    sa.Column('tg_id', sa.INTEGER(), nullable=False),
    sa.Column('event_type_id', sa.INTEGER(), nullable=False),
    sa.Column('is_dod', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['tg_event_types.id'], ),
    sa.ForeignKeyConstraint(['tg_id'], ['tg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tg_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tg_events_time'), ['time'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_events_tg_id'), ['tg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_events_event_type_id'), ['event_type_id'], unique=False)

    op.create_table('changed_plans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('visit_date', sa.DATETIME(), nullable=False),
    sa.Column('plan_id', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_ids.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('changed_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_changed_plans_id'), ['id'], unique=False)

    op.create_table('started_ways',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('visit_date', sa.DATETIME(), nullable=False),
    sa.Column('start_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('end_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('success', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_ids.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('started_ways', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_started_ways_id'), ['id'], unique=False)

    op.create_table('selected_auditories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('visit_date', sa.DATETIME(), nullable=False),
    sa.Column('auditory_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('success', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_ids.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('selected_auditories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_selected_auditories_id'), ['id'], unique=False)

    op.create_table('tg_event_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tg_event_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tg_event_types_name'), ['name'], unique=1)
        batch_op.create_index(batch_op.f('ix_tg_event_types_id'), ['id'], unique=False)

    op.create_table('tg_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tg_id', sa.BIGINT(), nullable=False),
    sa.Column('creation_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    with op.batch_alter_table('tg_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tg_users_tg_id'), ['tg_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_tg_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tg_users_creation_date'), ['creation_date'], unique=False)

    op.create_table('site_statistics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('visit_date', sa.DATETIME(), nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_ids.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_statistics_id'), ['id'], unique=False)

    op.create_table('user_ids',
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('creation_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###
