"""empty message

Revision ID: 36eaca93b5fb
Revises: 9098dc1d4b10
Create Date: 2025-05-28 18:08:02.741959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36eaca93b5fb'
down_revision: Union[str, None] = '9098dc1d4b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('started_ways', sa.Column('success', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('started_ways', 'success')
    # ### end Alembic commands ###
