"""Create tables for navigation data

Revision ID: 4acb0863f0c4
Revises: 54cc0e9009ab
Create Date: 2025-11-19 14:49:24.141425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4acb0863f0c4'
down_revision: Union[str, None] = '54cc0e9009ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sys', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('short', sa.String(length=2), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('metro', sa.String(length=100), nullable=False),
    sa.Column('crossings', sa.Text(), nullable=True),
    sa.Column('comments', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sys')
    )
    op.create_table('statics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ext', sa.String(length=6), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('corpuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sys', sa.String(length=7), nullable=False),
    sa.Column('loc_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('stair_groups', sa.Text(), nullable=True),
    sa.Column('comments', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['loc_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sys')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sys', sa.String(length=20), nullable=False),
    sa.Column('cor_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('entrances', sa.Text(), nullable=False),
    sa.Column('graph', sa.Text(), nullable=False),
    sa.Column('svg_id', sa.Integer(), nullable=True),
    sa.Column('nearest_entrance', sa.String(length=50), nullable=True),
    sa.Column('nearest_man_wc', sa.String(length=50), nullable=True),
    sa.Column('nearest_woman_wc', sa.String(length=50), nullable=True),
    sa.Column('nearest_shared_wc', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cor_id'], ['corpuses.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.ForeignKeyConstraint(['svg_id'], ['statics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sys')
    )
    op.create_table('auditories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sys', sa.String(length=50), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('text_from_sign', sa.String(length=200), nullable=True),
    sa.Column('additional_info', sa.String(length=200), nullable=True),
    sa.Column('comments', sa.String(length=200), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['statics.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sys')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditories')
    op.drop_table('plans')
    op.drop_table('corpuses')
    op.drop_table('types')
    op.drop_table('statics')
    op.drop_table('locations')
    op.drop_table('floors')
    # ### end Alembic commands ###
