"""add fio and dates to users

Revision ID: 6080e7ca7e97
Revises: 9f1d5d84c1ab
Create Date: 2026-02-22 01:08:36.838425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6080e7ca7e97'
down_revision: Union[str, None] = '9f1d5d84c1ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fio', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), server_default=sa.func.now(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
        batch_op.add_column(sa.Column('token_expired_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_expired_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('registration_date')
        batch_op.drop_column('fio')

    # ### end Alembic commands ###
