"""add creation_date to tg_users

Revision ID: 7f385d04c10a
Revises: aa3474cf3975
Create Date: 2026-03-15 20:23:05.242448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f385d04c10a'
down_revision: Union[str, None] = '1d4cf4d7f8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tg_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tg_users_creation_date'), ['creation_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tg_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tg_users_creation_date'))
        batch_op.drop_column('creation_date')

    # ### end Alembic commands ###
