"""Initial commit

Revision ID: ca63b3dbe208
Revises:
Create Date: 2025-01-03 16:40:20.297764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca63b3dbe208'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_ids',
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('creation_date', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table(
        'selected_auditories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('visit_date', sa.DateTime(), nullable=False),
        sa.Column('auditory_id', sa.String(length=50), nullable=False),
        sa.Column('success', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user_ids.user_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_selected_auditories_id'),
        'selected_auditories',
        ['id'],
        unique=False
    )
    op.create_table(
        'site_statistics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('visit_date', sa.DateTime(), nullable=False),
        sa.Column('endpoint', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user_ids.user_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_site_statistics_id'),
        'site_statistics',
        ['id'],
        unique=False
    )
    op.create_table(
        'started_ways',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('visit_date', sa.DateTime(), nullable=False),
        sa.Column('start_id', sa.String(length=50), nullable=False),
        sa.Column('end_id', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user_ids.user_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_started_ways_id'),
        'started_ways',
        ['id'],
        unique=False
    )
    op.create_table(
        'changed_plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('visit_date', sa.DateTime(), nullable=False),
        sa.Column('plan_id', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user_ids.user_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_changed_plans_id'),
        'changed_plans',
        ['id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_changed_plans_id'), table_name='changed_plans')
    op.drop_table('changed_plans')
    op.drop_index(op.f('ix_started_ways_id'), table_name='started_ways')
    op.drop_table('started_ways')
    op.drop_index(
        op.f('ix_site_statistics_id'),
        table_name='site_statistics'
    )
    op.drop_table('site_statistics')
    op.drop_index(
        op.f('ix_selected_auditories_id'),
        table_name='selected_auditories'
    )
    op.drop_table('selected_auditories')
    op.drop_table('user_ids')
    # ### end Alembic commands ###
