"""add can_grant to role_right_goals

Revision ID: d38504baa564
Revises: b5a10313c59b
Create Date: 2026-04-22 16:47:00.263301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd38504baa564'
down_revision: Union[str, None] = 'b5a10313c59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


RIGHT_GRANT_ID = 5
ROLE_ADMIN_ID = 1
GOAL_ROLES_ID = 4


rights = sa.table(
    'rights',
    sa.column('id', sa.Integer),
    sa.column('name', sa.String),
)

role_right_goals = sa.table(
    'role_right_goals',
    sa.column('role_id', sa.Integer),
    sa.column('right_id', sa.Integer),
    sa.column('goal_id', sa.Integer),
    sa.column('can_grant', sa.Boolean),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_right_goals', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('can_grant', sa.Boolean(), server_default=sa.false(), nullable=False)
        )
    # ### end Alembic commands ###

    connection = op.get_bind()

    connection.execute(
        sa.delete(role_right_goals).where(role_right_goals.c.right_id == RIGHT_GRANT_ID)
    )
    connection.execute(
        sa.delete(rights).where(rights.c.id == RIGHT_GRANT_ID)
    )
    connection.execute(
        sa.update(role_right_goals)
        .where(role_right_goals.c.role_id == ROLE_ADMIN_ID)
        .values(can_grant=True)
    )


def downgrade() -> None:
    connection = op.get_bind()

    grant_exists = connection.execute(
        sa.select(rights.c.id).where(rights.c.id == RIGHT_GRANT_ID)
    ).scalar_one_or_none()

    if grant_exists is None:
        connection.execute(
            sa.insert(rights).values(id=RIGHT_GRANT_ID, name='grant')
        )

    admin_grant_exists = connection.execute(
        sa.select(role_right_goals.c.role_id).where(
            role_right_goals.c.role_id == ROLE_ADMIN_ID,
            role_right_goals.c.right_id == RIGHT_GRANT_ID,
            role_right_goals.c.goal_id == GOAL_ROLES_ID,
        )
    ).scalar_one_or_none()

    if admin_grant_exists is None:
        connection.execute(
            sa.insert(role_right_goals).values(
                role_id=ROLE_ADMIN_ID,
                right_id=RIGHT_GRANT_ID,
                goal_id=GOAL_ROLES_ID,
                can_grant=True,
            )
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_right_goals', schema=None) as batch_op:
        batch_op.drop_column('can_grant')
    # ### end Alembic commands ###
