"""Update database scheme to hold status for review

Revision ID: e50b31c48695
Revises: 6a42eecaed1b
Create Date: 2025-11-30 12:35:01.781653

"""
from typing import Sequence, Union
from app.helpers.data import review_status
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e50b31c48695'
down_revision: Union[str, None] = '6a42eecaed1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def data_upgrades():
    review_statuses_table = sa.sql.table(
        "review_statuses",
        sa.sql.column('id', sa.Integer),
        sa.sql.column('name', sa.String(length=255)),
    )
    op.bulk_insert(
        review_statuses_table,
        list([{'id': id_, 'name': name} for id_, name in review_status.items()])
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('reviews') as batch_op:
        batch_op.add_column(sa.Column('review_status_id', sa.Integer(), server_default=sa.text('1'), nullable=False))
        batch_op.create_foreign_key('fk_reviews_review_status_id', 'review_statuses', ['review_status_id'], ['id'])

    data_upgrades()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews') as batch_op:
        batch_op.drop_constraint('fk_reviews_review_status_id', type_='foreignkey')
        batch_op.drop_column('review_status_id')

    op.drop_table('review_statuses')
    # ### end Alembic commands ###
