from .auditory import (
    DodNavAuditoryInput,
    DodNavAuditoryType,
    DodNavAuditoryUpdateInput,
    create_dod_nav_auditory,
    delete_dod_nav_auditory,
    resolve_dod_nav_auditories,
    update_dod_nav_auditory,
)
from .campus import (
    DodNavCampusInput,
    DodNavCampusType,
    DodNavCampusUpdateInput,
    create_dod_nav_campus,
    delete_dod_nav_campus,
    resolve_dod_nav_campuses,
    update_dod_nav_campus,
)
from .floor import (
    DodNavFloorInput,
    DodNavFloorType,
    DodNavFloorUpdateInput,
    create_dod_nav_floor,
    delete_dod_nav_floor,
    resolve_dod_nav_floors,
    update_dod_nav_floor,
)
from .location import (
    DodNavLocationInput,
    DodNavLocationType,
    DodNavLocationUpdateInput,
    create_dod_nav_location,
    delete_dod_nav_location,
    resolve_dod_nav_locations,
    update_dod_nav_location,
)
from .nav_type import (
    DodNavTypeInput,
    DodNavTypeType,
    DodNavTypeUpdateInput,
    create_dod_nav_type,
    delete_dod_nav_type,
    resolve_dod_nav_types,
    update_dod_nav_type,
)
from .plan import (
    DodNavPlanInput,
    DodNavPlanType,
    DodNavPlanUpdateInput,
    create_dod_nav_plan,
    delete_dod_nav_plan,
    resolve_dod_nav_plans,
    update_dod_nav_plan,
)
from .static import (
    DodNavStaticInput,
    DodNavStaticType,
    DodNavStaticUpdateInput,
    create_dod_nav_static,
    delete_dod_nav_static,
    resolve_dod_nav_statics,
    update_dod_nav_static,
)

__all__ = [
    "DodNavAuditoryInput",
    "DodNavAuditoryType",
    "DodNavAuditoryUpdateInput",
    "create_dod_nav_auditory",
    "delete_dod_nav_auditory",
    "resolve_dod_nav_auditories",
    "update_dod_nav_auditory",
    "DodNavCampusInput",
    "DodNavCampusType",
    "DodNavCampusUpdateInput",
    "create_dod_nav_campus",
    "delete_dod_nav_campus",
    "resolve_dod_nav_campuses",
    "update_dod_nav_campus",
    "DodNavFloorInput",
    "DodNavFloorType",
    "DodNavFloorUpdateInput",
    "create_dod_nav_floor",
    "delete_dod_nav_floor",
    "resolve_dod_nav_floors",
    "update_dod_nav_floor",
    "DodNavLocationInput",
    "DodNavLocationType",
    "DodNavLocationUpdateInput",
    "create_dod_nav_location",
    "delete_dod_nav_location",
    "resolve_dod_nav_locations",
    "update_dod_nav_location",
    "DodNavTypeInput",
    "DodNavTypeType",
    "DodNavTypeUpdateInput",
    "create_dod_nav_type",
    "delete_dod_nav_type",
    "resolve_dod_nav_types",
    "update_dod_nav_type",
    "DodNavPlanInput",
    "DodNavPlanType",
    "DodNavPlanUpdateInput",
    "create_dod_nav_plan",
    "delete_dod_nav_plan",
    "resolve_dod_nav_plans",
    "update_dod_nav_plan",
    "DodNavStaticInput",
    "DodNavStaticType",
    "DodNavStaticUpdateInput",
    "create_dod_nav_static",
    "delete_dod_nav_static",
    "resolve_dod_nav_statics",
    "update_dod_nav_static",
]



