name: Python CI

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - run: uv sync --frozen --dev --group lint
      - name: Ruff Check
        run: uv run ruff check . --output-format=github
      - name: Ruff Format
        run: uv run ruff format --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - run: uv sync --dev --frozen
      - run: uv run pytest
